global:
  scrape_interval: 10s # Як часто збирати дані

scrape_configs:
  - job_name: 'node_metrics'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'docker_containers'
    static_configs:
      - targets: ['prometheus:9090']
